<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Generate a report ID.
     *
     * @return string
     */
    private function generateReportId(){
        $timestamp = microtime();
        $randomPart = strtoupper(substr(hash('sha256', $timestamp), 0, 8));
        $reportId = 'RPT-' . $randomPart; 
        return $reportId;
    }

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('reports', function (Blueprint $table) {
            $table->string('report_id')->after('id'); // Add new column after 'id'
        });

        // Fill the new column with new IDs generated by generateReportId() function
        $reports = DB::table('reports')->get();
        foreach ($reports as $report) {
            $newId = $this->generateReportId();
            DB::table('reports')->where('id', $report->id)->update(['report_id' => $newId]);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
};
