<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class AlterConsultationsTableChangeIdColumnType extends Migration
{
    /**
     * Generate a consultation ID.
     *
     * @return string
     */
    private function generateConsultationId(){
        $timestamp = microtime();
        $randomPart = strtoupper(substr(hash('sha256', $timestamp), 0, 8));
        return $randomPart;
    }
    
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('consultations', function (Blueprint $table) {
            $table->string('consultation_id')->after('id'); // Add new column after 'id'
        });

        // Fill the new column with new IDs generated by generateConsultationId() function
        $consultations = DB::table('consultations')->get();
        foreach ($consultations as $consultation) {
            $newId = $this->generateConsultationId();
            DB::table('consultations')->where('id', $consultation->id)->update(['consultation_id' => $newId]);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        // If needed, you can implement the logic to rollback the migration
    }
}